# Generated by Django 3.1 on 2021-06-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_contactform_corporateenquiryform'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatanForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=30)),
                ('lastName', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('insta', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('referal', models.CharField(blank=True, max_length=30)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='corporateenquiryform',
            name='budget',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='corporateenquiryform',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
